import type { RouteManifest } from "~/app/routing/routeManifest"

export const ADMIN_HOME_PATH = "/overview"
export const ADMIN_LOGIN_PATH = "/login"
export const ADMIN_SPLASH_PATH = "/splash"

export const ADMIN_ROUTES: RouteManifest = [
  {
    id: "splash",
    path: ADMIN_SPLASH_PATH,
    title: "Starting",
    access: "public",
    element: () => import("~/features/auth/SplashScreen"),
    back: { kind: "exit" },
  },
  {
    id: "login",
    path: ADMIN_LOGIN_PATH,
    title: "Administrator sign in",
    access: "public",
    element: () => import("~/features/auth/LoginScreen"),
    back: { kind: "exit" },
  },
  {
    id: "overview",
    path: ADMIN_HOME_PATH,
    title: "Overview",
    access: "session",
    role: "admin",
    element: () => import("~/features/admin/overview/OverviewScreen"),
    nav: { domain: "overview", order: 1, label: "Overview", primary: true },
    back: { kind: "exit" },
  },
  {
    id: "applications",
    path: "/applications",
    title: "Applications",
    access: "session",
    role: "admin",
    permissions: ["applications.read"],
    element: () => import("~/features/admin/applications/ApplicationQueueScreen"),
    nav: { domain: "applications", order: 2, label: "Applications", primary: true },
    back: { kind: "parent", path: ADMIN_HOME_PATH },
  },
  {
    id: "application-detail",
    path: "/applications/:applicationId",
    title: "Application",
    access: "session",
    role: "admin",
    permissions: ["applications.read"],
    element: () => import("~/features/admin/applications/ApplicationDetailScreen"),
    back: { kind: "parent", path: "/applications" },
  },
  {
    id: "users",
    path: "/users",
    title: "Users",
    access: "session",
    role: "admin",
    permissions: ["users.read", "users.read_limited"],
    element: () => import("~/features/admin/users/UserDirectoryScreen"),
    nav: { domain: "users", order: 3, label: "Users" },
    back: { kind: "parent", path: ADMIN_HOME_PATH },
  },
  {
    id: "user-detail",
    path: "/users/:userId",
    title: "User",
    access: "session",
    role: "admin",
    permissions: ["users.read", "users.read_limited"],
    element: () => import("~/features/admin/users/UserDetailScreen"),
    back: { kind: "parent", path: "/users" },
  },
  {
    id: "user-login-events",
    path: "/users/:userId/login-events",
    title: "Login events",
    access: "session",
    role: "admin",
    permissions: ["users.read"],
    element: () => import("~/features/admin/users/UserLoginEventsScreen"),
    back: { kind: "parent", path: "/users/:userId" },
  },
  {
    id: "funds",
    path: "/funds",
    title: "Funds",
    access: "session",
    role: "admin",
    permissions: ["funds.read"],
    element: () => import("~/features/admin/funds/FundListScreen"),
    nav: { domain: "funds", order: 4, label: "Funds", primary: true },
    back: { kind: "parent", path: ADMIN_HOME_PATH },
  },
  {
    id: "fund-create",
    path: "/funds/new",
    title: "New fund",
    access: "session",
    role: "admin",
    permissions: ["funds.write"],
    requiresAll: ["funds.write", "aum.write"],
    element: () => import("~/features/admin/funds/FundCreateScreen"),
    back: { kind: "parent", path: "/funds" },
  },
  {
    id: "fund-workspace",
    path: "/funds/:fundId",
    title: "Fund workspace",
    access: "session",
    role: "admin",
    permissions: ["funds.read"],
    element: () => import("~/features/admin/funds/FundWorkspaceScreen"),
    back: { kind: "parent", path: "/funds" },
  },
  {
    id: "fund-holdings",
    path: "/funds/:fundId/holdings",
    title: "Holdings",
    access: "session",
    role: "admin",
    permissions: ["funds.read"],
    element: () => import("~/features/admin/funds/FundHoldingsScreen"),
    back: { kind: "parent", path: "/funds/:fundId" },
  },
  {
    id: "fund-aum",
    path: "/funds/:fundId/aum",
    title: "Fund AUM",
    access: "session",
    role: "admin",
    permissions: ["aum.read"],
    requiresAll: ["funds.read"],
    element: () => import("~/features/admin/fund-aum/FundAumScreen"),
    back: { kind: "parent", path: "/funds/:fundId" },
  },
  {
    id: "fund-aum-history",
    path: "/funds/:fundId/aum/history",
    title: "AUM history",
    access: "session",
    role: "admin",
    permissions: ["aum.read"],
    element: () => import("~/features/admin/fund-aum/FundAumHistoryScreen"),
    back: { kind: "parent", path: "/funds/:fundId/aum" },
  },
  {
    id: "aum",
    path: "/aum",
    title: "AUM",
    access: "session",
    role: "admin",
    permissions: ["aum.read"],
    requiresAll: ["funds.read"],
    element: () => import("~/features/admin/fund-aum/AumOverviewScreen"),
    nav: { domain: "aum", order: 5, label: "AUM" },
    back: { kind: "parent", path: ADMIN_HOME_PATH },
  },
  {
    id: "aum-collective",
    path: "/aum/collective",
    title: "Collective AUM growth",
    access: "session",
    role: "admin",
    permissions: ["aum.write"],
    element: () => import("~/features/admin/fund-aum/CollectiveAumGrowthScreen"),
    back: { kind: "parent", path: "/aum" },
  },
  {
    id: "client-values",
    path: "/client-values",
    title: "Client values",
    access: "session",
    role: "admin",
    permissions: ["client_values.read", "users.read", "users.read_limited"],
    element: () => import("~/features/admin/client-values/ClientPositionsScreen"),
    nav: { domain: "client-values", order: 6, label: "Client values" },
    back: { kind: "parent", path: ADMIN_HOME_PATH },
  },
  {
    id: "client-values-individual",
    path: "/client-values/individual",
    title: "Individual adjustment",
    access: "session",
    role: "admin",
    permissions: ["client_growth.write"],
    element: () => import("~/features/admin/client-values/IndividualClientGrowthScreen"),
    back: { kind: "parent", path: "/client-values" },
  },
  {
    id: "client-values-collective",
    path: "/client-values/collective",
    title: "Collective growth",
    access: "session",
    role: "admin",
    permissions: ["client_growth.write"],
    element: () => import("~/features/admin/client-values/CollectiveClientGrowthScreen"),
    back: { kind: "parent", path: "/client-values" },
  },
  {
    id: "receipts",
    path: "/receipts",
    title: "Fund receipts",
    access: "session",
    role: "admin",
    permissions: ["funds.receipts.read"],
    element: () => import("~/features/admin/receipts/FundReceiptQueueScreen"),
    nav: { domain: "money", order: 7, label: "Receipts", primary: true },
    back: { kind: "parent", path: ADMIN_HOME_PATH },
  },
  {
    id: "receipt-detail",
    path: "/receipts/:orderId",
    title: "Receipt",
    access: "session",
    role: "admin",
    permissions: ["funds.receipts.read"],
    element: () => import("~/features/admin/receipts/FundReceiptDetailScreen"),
    back: { kind: "parent", path: "/receipts" },
  },
  {
    id: "refunds",
    path: "/refunds",
    title: "Refunds",
    access: "session",
    role: "admin",
    permissions: ["refunds.write"],
    element: () => import("~/features/admin/refunds/RefundQueueScreen"),
    nav: { domain: "money", order: 8, label: "Refunds" },
    back: { kind: "parent", path: ADMIN_HOME_PATH },
  },
  {
    id: "payments",
    path: "/payments",
    title: "Payments",
    access: "session",
    role: "admin",
    permissions: ["payments.read"],
    element: () => import("~/features/admin/payments/PaymentEvidenceScreen"),
    nav: { domain: "money", order: 9, label: "Payments" },
    back: { kind: "parent", path: ADMIN_HOME_PATH },
  },
  {
    id: "mandates",
    path: "/mandates",
    title: "Mandates",
    access: "session",
    role: "admin",
    permissions: ["payments.read"],
    element: () => import("~/features/admin/mandates/MandateListScreen"),
    nav: { domain: "money", order: 10, label: "Mandates" },
    back: { kind: "parent", path: ADMIN_HOME_PATH },
  },
  {
    id: "mandate-detail",
    path: "/mandates/:mandateId",
    title: "Mandate",
    access: "session",
    role: "admin",
    permissions: ["payments.read"],
    element: () => import("~/features/admin/mandates/MandateDetailScreen"),
    back: { kind: "parent", path: "/mandates" },
  },
  {
    id: "audit",
    path: "/audit",
    title: "Audit log",
    access: "session",
    role: "admin",
    permissions: ["audit.read"],
    element: () => import("~/features/admin/audit/AuditLogScreen"),
    nav: { domain: "system", order: 11, label: "Audit" },
    back: { kind: "parent", path: ADMIN_HOME_PATH },
  },
  {
    id: "emails",
    path: "/emails",
    title: "Email deliveries",
    access: "session",
    role: "admin",
    permissions: ["email_deliveries.read", "email_deliveries.read_masked"],
    element: () => import("~/features/admin/emails/EmailDeliveriesScreen"),
    nav: { domain: "system", order: 12, label: "Emails" },
    back: { kind: "parent", path: ADMIN_HOME_PATH },
  },
  {
    id: "content-faqs",
    path: "/content/faqs",
    title: "FAQs",
    access: "session",
    role: "admin",
    permissions: ["content.read"],
    element: () => import("~/features/admin/content/FaqListScreen"),
    nav: { domain: "system", order: 13, label: "FAQs" },
    back: { kind: "parent", path: ADMIN_HOME_PATH },
  },
  {
    id: "app-config",
    path: "/app-config",
    title: "App configuration",
    access: "session",
    role: "admin",
    permissions: ["config.read"],
    element: () => import("~/features/admin/app-config/AppConfigBuilderScreen"),
    nav: { domain: "system", order: 14, label: "App config" },
    back: { kind: "parent", path: ADMIN_HOME_PATH },
  },
  {
    id: "not-found",
    path: "*",
    title: "Not found",
    access: "session",
    element: () => import("~/features/auth/NotFoundScreen"),
    back: { kind: "home" },
  },
]

export const ADMIN_GUARD_DESTINATIONS: readonly string[] = ["not-found"]

export const ADMIN_NAV_DOMAINS: Readonly<Record<string, string>> = {
  overview: "Overview",
  applications: "Applications",
  users: "Users",
  funds: "Funds",
  aum: "AUM",
  "client-values": "Client values",
  money: "Money",
  system: "System",
}

export const ADMIN_LINK_MAP: Readonly<Record<string, readonly string[]>> = {
  overview: ["applications", "users", "funds", "receipts", "payments", "audit"],
  applications: ["application-detail"],
  users: ["user-detail"],
  "user-detail": ["user-login-events"],
  funds: ["fund-create", "fund-workspace"],
  "fund-workspace": ["fund-holdings", "fund-aum"],
  "fund-aum": ["fund-aum-history"],
  aum: ["aum-collective", "fund-aum"],
  "client-values": ["client-values-individual", "client-values-collective"],
  receipts: ["receipt-detail"],
  mandates: ["mandate-detail"],
  "app-config": [],
}
