import type { RouteManifest } from "~/app/routing/routeManifest"

export const CLIENT_HOME_PATH = "/dashboard"
export const CLIENT_LOGIN_PATH = "/login"
export const CLIENT_SPLASH_PATH = "/splash"
export const CLIENT_VERIFY_EMAIL_PATH = "/verify-email"
export const CLIENT_BLOCKED_PATH = "/blocked"
export const CLIENT_SUPPORT_PATH = "/profile/support"

export const CLIENT_ROUTES: RouteManifest = [
  {
    id: "splash",
    path: CLIENT_SPLASH_PATH,
    title: "Starting",
    access: "public",
    element: () => import("~/features/auth/SplashScreen"),
    back: { kind: "exit" },
  },
  {
    id: "login",
    path: CLIENT_LOGIN_PATH,
    title: "Sign in",
    access: "public",
    element: () => import("~/features/auth/LoginScreen"),
    back: { kind: "exit" },
  },
  {
    id: "blocked",
    path: CLIENT_BLOCKED_PATH,
    title: "Account unavailable",
    access: "session",
    allowTerminalAccount: true,
    element: () => import("~/features/auth/BlockedScreen"),
    back: { kind: "exit" },
  },
  {
    id: "verify-email",
    path: CLIENT_VERIFY_EMAIL_PATH,
    title: "Verify your email",
    access: "session",
    role: "client",
    element: () => import("~/features/email-verification/EmailVerificationScreen"),
    back: { kind: "home" },
  },
  {
    id: "dashboard",
    path: CLIENT_HOME_PATH,
    title: "Home",
    access: "session",
    role: "client",
    element: () => import("~/features/dashboard/DashboardScreen"),
    nav: { domain: "home", order: 1, label: "Home", primary: true },
    back: { kind: "exit" },
  },
  {
    id: "funds",
    path: "/funds",
    title: "Funds",
    access: "session",
    role: "client",
    element: () => import("~/features/funds/FundListScreen"),
    nav: { domain: "funds", order: 2, label: "Funds", primary: true },
    back: { kind: "parent", path: CLIENT_HOME_PATH },
  },
  {
    id: "fund-detail",
    path: "/funds/:fundId",
    title: "Fund",
    access: "session",
    role: "client",
    element: () => import("~/features/funds/FundDetailScreen"),
    back: { kind: "parent", path: "/funds" },
  },
  {
    id: "invest-lumpsum",
    path: "/funds/:fundId/invest/lumpsum",
    title: "Invest a lump sum",
    access: "eligible",
    role: "client",
    element: () => import("~/features/orders/LumpsumInvestScreen"),
    back: { kind: "parent", path: "/funds/:fundId" },
    transactional: true,
  },
  {
    id: "invest-sip",
    path: "/funds/:fundId/invest/sip",
    title: "Start a SIP",
    access: "eligible",
    role: "client",
    element: () => import("~/features/sip/SipStartScreen"),
    back: { kind: "parent", path: "/funds/:fundId" },
    transactional: true,
  },
  {
    id: "portfolio",
    path: "/portfolio",
    title: "Portfolio",
    access: "session",
    role: "client",
    element: () => import("~/features/portfolio/PortfolioScreen"),
    nav: { domain: "portfolio", order: 3, label: "Portfolio", primary: true },
    back: { kind: "parent", path: CLIENT_HOME_PATH },
  },
  {
    id: "activity",
    path: "/activity",
    title: "Activity",
    access: "session",
    role: "client",
    element: () => import("~/features/activity/ActivityScreen"),
    nav: { domain: "activity", order: 4, label: "Activity", primary: true },
    back: { kind: "parent", path: CLIENT_HOME_PATH },
  },
  {
    id: "payment-status",
    path: "/activity/payments/:paymentId",
    title: "Payment",
    access: "eligible",
    role: "client",
    element: () => import("~/features/payments/PaymentStatusScreen"),
    back: { kind: "parent", path: "/activity" },
    transactional: true,
  },
  {
    id: "sips",
    path: "/sips",
    title: "SIP plans",
    access: "session",
    role: "client",
    element: () => import("~/features/sip/SipListScreen"),
    back: { kind: "parent", path: "/portfolio" },
  },
  {
    id: "sip-detail",
    path: "/sips/:sipPlanId",
    title: "SIP plan",
    access: "session",
    role: "client",
    element: () => import("~/features/sip/SipDetailScreen"),
    back: { kind: "parent", path: "/sips" },
  },
  {
    id: "statements",
    path: "/statements",
    title: "Statements",
    access: "session",
    role: "client",
    element: () => import("~/features/statements/StatementsScreen"),
    back: { kind: "parent", path: "/profile" },
  },
  {
    id: "notifications",
    path: "/notifications",
    title: "Notifications",
    access: "session",
    role: "client",
    element: () => import("~/features/notifications/NotificationsScreen"),
    back: { kind: "parent", path: CLIENT_HOME_PATH },
  },
  {
    id: "profile",
    path: "/profile",
    title: "Profile",
    access: "session",
    role: "client",
    element: () => import("~/features/profile/ProfileScreen"),
    nav: { domain: "profile", order: 5, label: "Profile", primary: true },
    back: { kind: "parent", path: CLIENT_HOME_PATH },
  },
  {
    id: "profile-email-verification",
    path: "/profile/email-verification",
    title: "Email verification",
    access: "session",
    role: "client",
    element: () => import("~/features/email-verification/VerificationStatusScreen"),
    back: { kind: "parent", path: "/profile" },
  },
  {
    id: "profile-security",
    path: "/profile/security",
    title: "Device security",
    access: "session",
    role: "client",
    element: () => import("~/features/device-security/DeviceSecurityScreen"),
    back: { kind: "parent", path: "/profile" },
  },
  {
    id: "profile-support",
    path: CLIENT_SUPPORT_PATH,
    title: "Support",
    access: "session",
    role: "client",
    allowTerminalAccount: true,
    element: () => import("~/features/support/SupportScreen"),
    back: { kind: "parent", path: "/profile" },
  },
  {
    id: "profile-legal",
    path: "/profile/legal",
    title: "Legal",
    access: "session",
    role: "client",
    element: () => import("~/features/legal/LegalScreen"),
    back: { kind: "parent", path: "/profile" },
  },
  {
    id: "investor-charter",
    path: "/profile/legal/investor-charter",
    title: "Investor charter",
    access: "session",
    role: "client",
    element: () => import("~/features/legal/InvestorCharterScreen"),
    back: { kind: "parent", path: "/profile/legal" },
  },
  {
    id: "grievance",
    path: "/profile/legal/grievance",
    title: "Grievance redressal",
    access: "session",
    role: "client",
    element: () => import("~/features/legal/GrievanceScreen"),
    back: { kind: "parent", path: "/profile/legal" },
  },
  {
    id: "not-found",
    path: "*",
    title: "Not found",
    access: "session",
    element: () => import("~/features/auth/NotFoundScreen"),
    back: { kind: "home" },
  },
]

export const CLIENT_GUARD_DESTINATIONS: readonly string[] = [
  "blocked",
  "verify-email",
  "not-found",
]

export const CLIENT_LINK_MAP: Readonly<Record<string, readonly string[]>> = {
  dashboard: ["funds", "portfolio", "activity", "notifications", "verify-email", "sips"],
  funds: ["fund-detail"],
  "fund-detail": ["invest-lumpsum", "invest-sip", "investor-charter", "grievance"],
  portfolio: ["fund-detail", "sips"],
  activity: ["payment-status"],
  sips: ["sip-detail"],
  profile: [
    "statements",
    "notifications",
    "profile-email-verification",
    "profile-security",
    "profile-support",
    "profile-legal",
  ],
  "profile-legal": ["investor-charter", "grievance"],
  blocked: ["profile-support", "login"],
  "invest-lumpsum": ["payment-status"],
  "invest-sip": ["sip-detail", "payment-status"],
  "sip-detail": ["payment-status"],
}
