#!/usr/bin/env bash
# ─────────────────────────────────────────────────────────────────────────────
# paths.sh — generator and reader for the per-stack `paths.json` contract.
#
# WHY THIS EXISTS
# The plan mandates "the paths will be supplied by the paths.json file", and the
# old scripts never read paths.json at all — every path was a string literal
# duplicated across local and remote code. That is the single biggest source of
# drift between this machine and the VPS.
#
# THE CONTRACT
# `paths.json` is a GENERATED artifact. lib/stacks.sh is the source of truth;
# this file serialises it. The same file is then read by:
#   • local scripts  (deploy.sh / rollback.sh / status.sh) — to know where to ship
#   • VPS scripts    (<stack>_deploy.sh / _rollback.sh)    — to know where to write
#
# Both sides therefore agree by construction. If a path needs to change, it
# changes in stacks.sh, is regenerated, and is shipped — never edited in two
# places.
#
# Regenerate with:  ./release_manager/status.sh → Regenerate stack artifacts
#              or:  paths_write <stack> <outfile>
# ─────────────────────────────────────────────────────────────────────────────

# paths_json <stack> — emit the paths.json document for one stack on stdout.
paths_json() {
    local stack="$1"
    is_stack "$stack" || { printf 'paths_json: unknown stack %s\n' "$stack" >&2; return 1; }

    local env_name short dir compose version_file deploy rollback guide lock
    local prefix project rollback_root images_sub apk_sub db_sub log_sub db_backup_sub
    local apk_dirs keep has_db log_prefix
    env_name="$(stack_attr "$stack" env)"
    short="$(stack_attr "$stack" short)"
    compose="$(stack_attr "$stack" compose)"
    version_file="$(stack_attr "$stack" version_file)"
    deploy="$(stack_attr "$stack" deploy)"
    rollback="$(stack_attr "$stack" rollback)"
    guide="$(stack_attr "$stack" guide)"
    prefix="$(stack_attr "$stack" prefix)"
    project="$(stack_attr "$stack" project)"
    rollback_root="$(stack_attr "$stack" rollback_root)"
    images_sub="$(stack_attr "$stack" images_sub)"
    apk_sub="$(stack_attr "$stack" apk_sub)"
    db_sub="$(stack_attr "$stack" db_sub)"
    log_sub="$(stack_attr "$stack" log_sub)"
    log_prefix="$(stack_attr "$stack" log_prefix)"
    db_backup_sub="$(stack_attr "$stack" db_backup_sub)"
    apk_dirs="$(stack_attr "$stack" apk_dirs)"
    keep="$(stack_attr "$stack" keep)"
    has_db="$(stack_attr "$stack" has_db)"
    dir="$(stack_dir "$stack")"
    lock="$(stack_lock "$stack")"

    # Image descriptors as a JSON array, derived from stack_images().
    local images_json='[]' line key archive port
    while IFS=: read -r key archive port; do
        [[ -n "$key" ]] || continue
        images_json="$(printf '%s' "$images_json" | jq \
            --arg key "$key" \
            --arg archive "$archive" \
            --argjson port "$port" \
            '. + [{key: $key, archive: $archive, container_port: $port}]')"
    done < <(stack_images "$stack")

    # APK holder directories as a JSON array.
    local apk_json='[]' d
    for d in $apk_dirs; do
        apk_json="$(printf '%s' "$apk_json" | jq --arg d "$d" '. + [$d]')"
    done

    jq -n \
        --arg schema "2" \
        --arg stack "$stack" \
        --arg environment "$env_name" \
        --arg short "$short" \
        --arg vps_root "$BOE_VPS_ROOT" \
        --arg stack_dir "$dir" \
        --arg compose "$compose" \
        --arg version_file "$version_file" \
        --arg deploy_script "$deploy" \
        --arg rollback_script "$rollback" \
        --arg guide "$guide" \
        --arg lock_file "$lock" \
        --arg container_prefix "$prefix" \
        --arg compose_project "$project" \
        --arg docker "$BOE_DOCKER" \
        --arg backup_root "$BOE_BACKUP_ROOT" \
        --arg backup_mount "$BOE_BACKUP_MOUNT" \
        --arg rollback_root "$rollback_root" \
        --arg images_sub "$images_sub" \
        --arg apk_sub "$apk_sub" \
        --arg db_sub "$db_sub" \
        --arg log_sub "$log_sub" \
        --arg log_prefix "$log_prefix" \
        --arg db_backup_sub "$db_backup_sub" \
        --argjson images "$images_json" \
        --argjson apk_dirs "$apk_json" \
        --argjson keep "$keep" \
        --argjson has_db "$has_db" \
        --arg generated_at "$(date -u +%Y-%m-%dT%H:%M:%SZ)" \
        '{
          schema: ($schema|tonumber),
          generated_at: $generated_at,
          note: "GENERATED by release_manager/lib/paths.sh from lib/stacks.sh. Do not hand-edit; regenerate and re-ship.",

          stack: $stack,
          environment: $environment,
          short: $short,

          vps: {
            root: $vps_root,
            stack_dir: $stack_dir,
            images_dir: ($stack_dir + "/images"),
            compose_file: ($stack_dir + "/" + $compose),
            compose_name: $compose,
            env_file: ($stack_dir + "/.env"),
            env_example: ($stack_dir + "/.env.example"),
            version_file: ($stack_dir + "/" + $version_file),
            version_name: $version_file,
            manifest_file: ($stack_dir + "/manifest.json"),
            checksums_file: ($stack_dir + "/checksums.sha256"),
            deploy_script: ($stack_dir + "/" + $deploy_script),
            rollback_script: ($stack_dir + "/" + $rollback_script),
            guide: ($stack_dir + "/" + $guide),
            registry: ($vps_root + "/manifest.json"),
            apk_dirs: ($apk_dirs | map($stack_dir + "/" + .)),
            docker: $docker,
            container_prefix: $container_prefix,
            compose_project: $compose_project,
            lock_file: $lock_file
          },

          backup: {
            mount_check: $backup_mount,
            root: $backup_root,
            rollback_root: $rollback_root,
            rollback_images: ($rollback_root + "/" + $images_sub),
            rollback_apk: ($rollback_root + "/" + $apk_sub),
            rollback_db: ($rollback_root + "/" + $db_sub),
            db_backups: ($backup_root + "/DB_BACKUPS/" + $db_backup_sub),
            emergency_db: ($backup_root + "/DBS_ROLLBACK"),
            logs_root: ($backup_root + "/LOGS/" + $log_sub),
            deploy_log: ($backup_root + "/LOGS/" + $log_sub + "/" + $log_prefix + "DEPLOY_LOGS"),
            image_log: ($backup_root + "/LOGS/" + $log_sub + "/" + $log_prefix + "IMAGE_LOGS"),
            db_log: ($backup_root + "/LOGS/" + $log_sub + "/" + $log_prefix + "PSQL_DB_LOGS"),
            app_log: ($backup_root + "/LOGS/" + $log_sub + "/" + $log_prefix + "APP_LOGS")
          },

          images: $images,
          has_database: $has_db,
          retention: { keep_releases: $keep }
        }'
}

# paths_write <stack> <outfile> — generate paths.json atomically.
paths_write() {
    local stack="$1" out="$2" tmp
    tmp="$(mktemp "${out}.XXXXXX")"
    if ! paths_json "$stack" > "$tmp"; then
        rm -f "$tmp"; return 1
    fi
    jq empty "$tmp" || { rm -f "$tmp"; printf 'Generated invalid JSON for %s\n' "$stack" >&2; return 1; }
    mv "$tmp" "$out"
}

# paths_get <paths.json> <jq-path> — read one value out of a paths.json file.
# Returns 1 (and prints nothing) if the key is absent, so callers can default.
paths_get() {
    local file="$1" query="$2" value
    [[ -f "$file" ]] || { printf 'paths.json not found: %s\n' "$file" >&2; return 1; }
    value="$(jq -r "$query // empty" "$file" 2>/dev/null)" || return 1
    [[ -n "$value" ]] || return 1
    printf '%s\n' "$value"
}
